# Generated by Django 5.1.1 on 2024-10-08 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('owner_name', models.CharField(max_length=70)),
                ('shop_no', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=150)),
                ('phone1', models.CharField(max_length=50)),
                ('phone2', models.CharField(blank=True, max_length=50, null=True)),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_mall.category')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_mall.shop')),
            ],
        ),
    ]
