# Generated by Django 5.1.1 on 2024-10-08 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_mall', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='shop_id',
            new_name='shop',
        ),
    ]
