# Generated by Django 5.1.1 on 2024-10-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_mall', '0004_product_brand_name_product_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='phone1',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone2',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_no',
            field=models.CharField(db_index=True, max_length=80, unique=True),
        ),
    ]
