# Generated by Django 5.1.1 on 2024-10-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_mall', '0005_alter_shop_phone1_alter_shop_phone2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='phone2',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
