# Generated by Django 5.1.1 on 2024-10-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_mall', '0006_alter_shop_phone2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='phone2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
