# Generated by Django 5.1.1 on 2024-10-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_mall', '0007_alter_shop_phone2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='phone1',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_no',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
